defaults: &defaults
  app_id: '474339089314884'
  app_secret: '2a1411f9ac1d497f5a7a1dcfc607d5a8'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  app_id: '632052596830438'
  app_secret: 'dcdeb1b3efb51a49bfffdd5abd3f893b'

