defaults: &defaults
  # app_id: '804756047277'
  # app_secret: 'DKC2xTwlYmy7-2UottwYiOey'

  app_id: '398807837988-icc8a1hbgjpo97pappun80n7lrnal68l.apps.googleusercontent.com'
  app_secret: '9qi32R1ojVNLOBEGftJxaGHo'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  # app_id: '538313000201'
  # app_secret: 'zy15LNLOBGIalPwCyW9n2rwF'
  <<: *defaults